language: nix
git:
  submodules: false
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//g' .gitmodules
  - git submodule update --init --recursive
install:
  - echo "trusted-users = $USER" | sudo tee -a /etc/nix/nix.conf
  - sudo systemctl restart nix-daemon
  - nix-env -iA nixpkgs.cachix
  - cachix use websites
script:
  - nix-build
