language: nix
nix: 2.3.10
cache:
  directories:
  - $HOME/nix.store
git:
  submodules: false
before_install:
  - sudo mkdir -p /etc/nix
  - echo "substituters = https://cache.nixos.org/ file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
  - echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null
  - sed -i 's/git@github.com:/https:\/\/github.com\//g' .gitmodules
  - git submodule update --init --recursive
  - nix-channel --add https://nixos.org/channels/nixos-20.09 nixpkgs
  - nix-channel --update
before_cache:
  - mkdir -p $HOME/nix.store
  - nix copy --to file://$HOME/nix.store -f default.nix buildInputs
install:
  - echo "trusted-users = $USER" | sudo tee -a /etc/nix/nix.conf
  - sudo systemctl restart nix-daemon
  - nix-env -iA nixpkgs.cachix
  - cachix use websites
before-script:
  - sudo mkdir -p /etc/nix && echo 'sandbox = true' | sudo tee -a /etc/nix/nix.conf
  - sudo systemctl restart nix-daemon
script:
  - cachix use websites
  - nix-build
