language: nix
nix: 2.3.10
git:
  submodules: false
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//g' .gitmodules
  - git submodule update --init --recursive
  - nix-channel --add https://nixos.org/channels/nixos-20.09 nixpkgs
  - nix-channel --update
install:
  - echo "trusted-users = $USER" | sudo tee -a /etc/nix/nix.conf
  - sudo systemctl restart nix-daemon
  - nix-env -iA nixpkgs.cachix
  - cachix use websites
before-script:
  - sudo mkdir -p /etc/nix && echo 'sandbox = true' | sudo tee -a /etc/nix/nix.conf
script:
  - cachix use websites
  - nix-build
