org: dandart
app: websites
service: websites

provider:
  name: aws
  region: eu-west-2
  runtime: haskell
  environment:
    LANG: en_GB.UTF-8
    LC_ALL: en_GB.UTF-8
  logs:
    restApi: false

functions:
  submit-comment:
    handler: websites.submit-comment
    name: ${self:provider.stage}-submit-comment
    events:
      - http:
          path: /comment
          method: post
          cors: true
          private: false

plugins:
  - serverless-haskell
  - serverless-offline
  #- serverless-http-invoker

custom:
  haskell:
    docker: true
    stackBuildArgs:
      - --allow-different-user
  serverless-offline:
    # useDocker: true
    # useChildProcesses: true
    printOutput: true