org: dandart
app: websites
service: websites

package:
  exclude:
    - ./**
  include:
    - bootstrap
    - submit-comment
    
provider:
  name: aws
  region: eu-west-2
  runtime: haskell
  environment:
    LANG: en_GB.UTF-8
    LC_ALL: en_GB.UTF-8
    GITHUB_ACCESS_TOKEN: ${env:GITHUB_ACCESS_TOKEN}
  logs:
    restApi: false
  apiGateway:
    shouldStartNameWithService: true

functions:
  submit-comment:
    handler: websites.submit-comment
    name: ${self:provider.stage}-submit-comment
    events:
      - http:
          path: /comment
          method: post
          cors: true
          private: false

plugins:
  - serverless-dotenv-plugin
  - serverless-haskell
  - serverless-offline

custom:
  haskell:
    docker: true
  serverless-offline:
    useDocker: true
    printOutput: true