org: dandart
app: websites
service: websites

package:
  exclude:
    - ./**
  include:
    - bootstrap
    - submit-comment
    - visit
    - visit-migrate
    - init.sql
    - lib/**
    
provider:
  name: aws
  region: eu-west-2
  runtime: haskell
  environment:
    LANG: en_GB.UTF-8
    LC_ALL: en_GB.UTF-8
    GITHUB_ACCESS_TOKEN: ${env:GITHUB_ACCESS_TOKEN}
  logs:
    restApi: false
  apiGateway:
    shouldStartNameWithService: true

functions:
  submit-comment:
    handler: websites.submit-comment
    name: ${self:provider.stage}-submit-comment
    events:
      - http:
          path: /comment
          method: post
          cors: true
          private: false
  
  visit-migrate:
    handler: websites.visit-migrate
    name: ${self:provider.stage}-visit-migrate
  
  visit:
    handler: websites.visit
    name: ${self:provider.stage}-visit
    events:
      - http:
          path: /visit.gif
          method: get
          cors: true
          private: false

resources:
  Parameters:
    DBUsername:
      NoEcho: 'true'
      Default: ${env:DB_USERNAME}
      Description: Username for MySQL database access
      Type: String
      MinLength: '1'
      MaxLength: '16'
      AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
      ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
    DBPassword:
      NoEcho: 'true'
      Default: ${env:DB_PASSWORD}
      Description: Password for MySQL database access
      Type: String
      MinLength: '8'
      MaxLength: '41'
      AllowedPattern: '[a-zA-Z0-9]*'
      ConstraintDescription: must contain only alphanumeric characters.
  Resources:
    visitsDB:
      Type: AWS::RDS::DBCluster
      Properties:
        MasterUsername: !Ref DBUsername
        MasterUserPassword: !Ref DBPassword
        DBClusterIdentifier: visits
        Engine: aurora
        # EngineVersion: 5.6.10a
        EngineMode: serverless
        ScalingConfiguration:
          AutoPause: true
          MaxCapacity: 2
          MinCapacity: 1
          SecondsUntilAutoPause: 300
        EnableHttpEndpoint: true
        StorageEncrypted: true

plugins:
  # - data-api-migrations-serverless
  # - data-api-local-serverless
  - serverless-dotenv-plugin
  - serverless-haskell
  - serverless-offline

custom:
  haskell:
    docker: true
  serverless-offline:
    useDocker: true
    printOutput: true
  #data-api-local:
  #  server:
  #    port: 8081
  #    hostname: localhost
  #  database:
  #    engine: postgres
  #    connectionString: ${env.DB_LOGIN}@${env.DB_PASSWORD}
  #data-api-migrations:
  #  local:
  #    region: ${self:provider.region}
  #    endpoint: http://localhost:8081
   #   maxRetries: 0
   #   #secretArn: ${self:provider.environment.DATA_API_SECRET_ARN}
  #    #resourceArn: ${self:provider.environment.DATA_API_RESOURCE_ARN}
  #    database: "visits" #${self:provider.environment.DATA_API_DATABASE_NAME}
  #    credentials:
  #      accessKeyId: example
  #      secretAccessKey: example
  #  prod:
  #    region: ${self:provider.region}
  #    secretArn: #${self:provider.environment.DATA_API_SECRET_ARN}
  #    resourceArn: #${self:provider.environment.DATA_API_RESOURCE_ARN}
  #    database: "visits" # ${self:provider.environment.DATA_API_DATABASE_NAME}