org: dandart
app: websites
service: websites

package:
  exclude:
    - ./**
  include:
    - bootstrap
    - .stack-work/dist/x86_64-linux-tinfo6/Cabal-3.2.0.0/build/submit-comment/submit-comment
    - .stack-work/dist/x86_64-linux-tinfo6/Cabal-3.2.0.0/build/submit-review-comment/submit-review-comment
  excludeDevDependencies: false

provider:
  name: aws
  region: eu-west-2
  runtime: provided
  environment:
    LANG: en_GB.UTF-8
    LC_ALL: en_GB.UTF-8
    GITHUB_ACCESS_TOKEN: ${env:GITHUB_ACCESS_TOKEN}
  logs:
    restApi: false
  apiGateway:
    shouldStartNameWithService: true

functions:
  submit-comment:
    handler: websites.submit-comment
    name: ${self:provider.stage}-submit-comment
    events:
      - http:
          path: /comment
          method: post
          cors: true
          private: false
  submit-review-comment:
    handler: websites.submit-review-comment
    name: ${self:provider.stage}-submit-review-comment
    events:
      - http:
          path: /review-comment
          method: post
          cors: true
          private: false

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  serverless-offline:
    useDocker: true
    # useChildProcesses: true
    printOutput: true