ghc-options:
  websites: -j16 -Wall -Werror
packages:
- .
extra-deps:
- serverless-haskell-0.12.4
- git: https://github.com/danwdart/fsutils.git
  commit: a4167c212939f7b2b123072542ad305777943903
- gogol-0.5.0
- gogol-core-0.5.0
- gogol-youtube-0.5.0
resolver: lts-16.25