resolver: nightly-2020-11-01
packages:
- .
extra-deps:
  -
    git: https://github.com/danwdart/fsutils.git
    commit: a4167c212939f7b2b123072542ad305777943903
ghc-options:
  websites: -j16 -Wall -Werror