resolver: lts-14.12
packages:
- .
extra-deps:
  - aeson-1.4.5.0
  - binary-0.8.7.0
  - blaze-html-0.9.1.1
  - blaze-markup-0.8.2.3
  - bytestring-0.10.8.1
  - directory-1.3.4.0
  - location:
    git: git@github.com:danwdart/fsutils.git
    commit: a4c4b287f126143ae058438c38372df5f0fe4eac
  - process-1.6.6.0
  - req-2.1.0
  - text-1.2.4.0
  - unix-2.7.2.2
ghc-options:
  web: -Wall -Werror