name: "Deploy all websites"
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  workflow_dispatch:
jobs:
  deploy-all-websites:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v11
      with:
        name: dandart
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: |
        git submodule update --init --recursive
        git submodule foreach git checkout master
        scripts/deploy.sh
